; user consts
WIDTH 					= 1024
HEIGHT 					= 768



; system consts
WS_OVERLAPPEDWINDOW 	            = 00cf0000h
CW_USEDEFAULT			            = 80000000h
WS_VISIBLE				            = 10000000h
WS_EX_COMPOSITED		            = 02000000h

COLOR_BTNFACE 			            = 15
IDC_ARROW  				            = 32512

WM_DESTROY                          = 0002h
WM_PAINT                            = 000Fh
WM_CREATE                           = 0001h
WM_KEYDOWN		                    = 0100h

FORMAT_MESSAGE_ALLOCATE_BUFFER 	    = 00000100h
FORMAT_MESSAGE_FROM_SYSTEM		    = 00001000h

LR_LOADFROMFILE     	            = 0010h
IMAGE_BITMAP       		            = 0
SRCCOPY     			            = 00CC0020h

CS_HREDRAW 				            = 00000002h
CS_VREDRAW 				            = 00000001h
